### ISSUE TITLE
Black Box

### ISSUE THREAD

**Issue by juturna01** [gposingway/gposingway#41]
If I missed something in the guide I apologize, but I'm struggling to figure out why basically every preset shows a transparent black box around certain things, like job gauges(Brd), and the little floating lights in the crystarium. When disabling the keep/restore ui it goes away, but then obviously the HUD elements look absurd haha.

**Comment by LeonAquitaine** [comment]
Hey @juturna01! This is a known interaction issue between `KeepUI.fx` and certain in-game visual elements. While there are no known fixes for the legacy shader, users have found the REST addon for ReShade to be a viable replacement (e.g. https://www.youtube.com/watch?v=uoSA9_xGiZM.) Since Gposingway relies on `KeepUI.fx` for legacy support of older preset collections, I won't be able to present a fix for this.
